blank_issues_enabled: false
contact_links:
  - name: ðŸ™‹ Need help or have a question?
    url: https://github.com/uloamaka/tabmax/discussions
    about: Please use GitHub Discussions for general questions.
